import SwiftUI

enum MCPixel: UInt8 {
    case empty = 0
    case outline = 1
    case fur = 2
    case dark = 3
    case light = 4
    case eye = 5
    case blink = 6
    case nose = 7
}

enum MCPalette {
    static func color(for pixel: MCPixel) -> Color {
        switch pixel {
        case .empty: return .clear
        case .outline: return Color(red: 0.25, green: 0.18, blue: 0.12)
        case .fur: return Color(red: 0.83, green: 0.63, blue: 0.29)
        case .dark: return Color(red: 0.55, green: 0.35, blue: 0.16)
        case .light: return Color(red: 0.94, green: 0.75, blue: 0.38)
        case .eye: return Color(red: 0.12, green: 0.11, blue: 0.10)
        case .blink: return Color(red: 0.55, green: 0.35, blue: 0.16)
        case .nose: return Color(red: 0.78, green: 0.45, blue: 0.42)
        }
    }
}

typealias MCPixelGrid = [[MCPixel]]

enum MCCatSprites {
    static let gridSize = 16

    static func grid(for frame: CatFrame) -> MCPixelGrid {
        switch frame {
        case .frontBase: return frontBase
        case .frontEar1: return frontEar1
        case .frontEar2: return frontEar2
        case .frontBlink: return frontBlink
        case .walkLeft1: return walkLeft1
        case .walkLeft2: return walkLeft2
        case .walkRight1: return mirror(walkLeft1)
        case .walkRight2: return mirror(walkLeft2)
        }
    }

    private static let frontBase: MCPixelGrid = parse("""
    ................
    .....kk..kk.....
    ....kffkkffd....
    ...kfffffffd....
    ..kfflfffffd....
    ..kfeffffefk....
    ..kfnffffnfk....
    ..kffddddfk.....
    ...kffffffk.....
    ...kffffffk.....
    ....kd...dk.....
    ....kd...dk.....
    ................
    ................
    ................
    ................
    """)

    private static let frontEar1: MCPixelGrid = parse("""
    ................
    ...kk...........
    ..kffkk..kk.....
    .kffffffkkffd...
    .kffflfffffd....
    .kfefffffefk....
    ..kfnffffnfk....
    ..kffddddfk.....
    ...kffffffk.....
    ...kffffffk.....
    ....kd...dk.....
    ....kd...dk.....
    ................
    ................
    ................
    ................
    """)

    private static let frontEar2: MCPixelGrid = parse("""
    ................
    ..........kk....
    .....kk..kkffk..
    ...dfffkkfffffk.
    ....dfflfffffk..
    ....kfeffffefk..
    .....kfnffffnfk.
    ....kffddddfk...
    ...kffffffk.....
    ...kffffffk.....
    ....kd...dk.....
    ....kd...dk.....
    ................
    ................
    ................
    ................
    """)

    private static let frontBlink: MCPixelGrid = parse("""
    ................
    .....kk..kk.....
    ....kffkkffd....
    ...kfffffffd....
    ..kfflfffffd....
    ..kfbffffbfk....
    ..kfnffffnfk....
    ..kffddddfk.....
    ...kffffffk.....
    ...kffffffk.....
    ....kd...dk.....
    ....kd...dk.....
    ................
    ................
    ................
    ................
    """)

    private static let walkLeft1: MCPixelGrid = parse("""
    ................
    ...........kk...
    ..........kffd..
    .........kfffd..
    ........kfflfd..
    .......kfeefd...
    .......kfnfd....
    ......kfffd.....
    .....kfffd......
    ....kfffd.......
    ...kdd..........
    ..kfd...........
    .kdd............
    ................
    ................
    ................
    """)

    private static let walkLeft2: MCPixelGrid = parse("""
    ................
    ...........kk...
    ..........kffd..
    .........kfffd..
    ........kfflfd..
    .......kfeefd...
    .......kfnfd....
    ......kfffd.....
    .....kfffd......
    ....kfffd.......
    .......kdd......
    ........kfd.....
    .........kdd....
    ................
    ................
    ................
    """)

    private static func mirror(_ grid: MCPixelGrid) -> MCPixelGrid {
        grid.map { row in
            let padded = row + Array(repeating: MCPixel.empty, count: max(0, gridSize - row.count))
            return Array(padded.prefix(gridSize).reversed())
        }
    }

    private static func parse(_ art: String) -> MCPixelGrid {
        art.split(separator: "\n").map { line in
            var row = Array(line.prefix(gridSize)).map { char -> MCPixel in
                switch char {
                case ".": return .empty
                case "k": return .outline
                case "f": return .fur
                case "d": return .dark
                case "l": return .light
                case "e": return .eye
                case "b": return .blink
                case "n": return .nose
                default: return .empty
                }
            }
            while row.count < gridSize { row.append(.empty) }
            return row
        }
    }
}
